version: '3.8'

services:
  # --- 1. DATABASE (MySQL) ---
  db:
    image: mysql:8.0
    container_name: kmovie_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Mật khẩu root (hãy nhớ cái này)
      MYSQL_DATABASE: kmovie        # Tên database sẽ được tạo tự động
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql        # Lưu dữ liệu để không mất khi tắt docker

  # --- 2. BACKEND (Node.js) ---
  backend:
    build: ./backend
    container_name: kmovie_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - PORT=5000
      # Cấu hình kết nối MySQL
      - DB_HOST=db             # Tên service mysql ở trên (QUAN TRỌNG: không dùng localhost)
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=kmovie
      - DB_PORT=3306
      - DB_DIALECT=mysql
      # Các key cũ của bạn
      - JWT_SECRET=leuleujwtcuatuine@1708
      - JWT_REFRESH_SECRET=refreshsecret@1708
      - JWT_EXPIRES_IN=1d
      - BCRYPT_SALT=10
      - CLOUDINARY_CLOUD_NAME=dx5awhwyx
      - CLOUDINARY_API_KEY=837125251727789
      - CLOUDINARY_API_SECRET=RpdUKIbmuva2rTZ2IvWoY9aH0jo
      - EMAIL_USER=dinhanhkiet510@gmail.com
      - EMAIL_PASS=tltv eszc bebl nhjf
      - GOOGLE_CLIENT_ID=1046523141260-3foh0nl6v5spif3vae804boh5oou0bbp.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - FACEBOOK_CLIENT_ID=123456789012345
      - FACEBOOK_CLIENT_SECRET=your_facebook_client_secret
      - FACEBOOK_REDIRECT_URI=http://localhost:5000/api/auth/facebook/callback

  # --- 3. FRONTEND (Nginx) ---
  # frontend:
  # build: ./frontend
  # container_name: kmovie_frontend
  # restart: always
  # ports:
  #   - "80:80"
  # depends_on:
  #   - backend

volumes:
  mysql_data: